# Workflow for converting diagrams and deploying static content to GitHub Pages
name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - "kubook/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Convert Excalidraw diagrams to images if diagrams changed
  converter:
    runs-on: ubuntu-latest
    outputs:
      diagrams-changed: ${{ steps.check-changes.outputs.diagrams-changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install excalirender
        run: curl -fsSL https://raw.githubusercontent.com/JonRC/excalirender/main/install.sh | sh

      - name: Run excalirender
        run: excalirender -r ./kubook/src/diagrams --transparent -s 2 -o ./kubook/src/images

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -f ./kubook/src/images
          git commit -m "Update excalidraw exports" || echo "No changes to commit"
          git push origin main

  # Build and deploy to GitHub Pages
  deploy:
    needs: converter
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build with mdBook
        run: |
          cargo install mdbook
          mdbook test kubook
          mdbook build kubook

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "kubook/book"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
